### ISSUE TITLE
Integration cannot be configured trough the UI

### ISSUE THREAD

**Issue by kimme1024** [Aohzan/hass-mcz-maestro#1]
Hi, 

First of all, thanks for making this, I think this will make everything a lot easier for people to connect their stove to HA.

However when I try to add the integration I'm getting an error that the integration cannot be configured trough the UI. After that there are no further options to proceed.

Any idea what may cause this?

I'm running the latest version of HA Core.

Thanks!

**Comment by Aohzan** [comment]
Hello,

I just pushed a fix, can you test the last version please ?

**Comment by kimme1024** [comment]
@Aohzan: Thanks, I can proceed now, however I don't have direct access to the stove on my HA-server. I'll have to look for a workaround...

**Comment by Aohzan** [comment]
Do you need a compatibility with the cloud connection ? I have to see if it's easy to implement

Otherwyse you just have to add a wifi network on yout server

**Comment by kimme1024** [comment]
I remember there have been some issues with connecting the original app when I got the stove, I quickly changed it using the MQTT way with a RPi (which works currently, but it isn't really reliable).
However if I can stop using the RPi using your integration that would be preferable.
It seems logic to just be able to connect the stove to my LAN, giving it an IP in my current subnet and directing your integration to that ip.
However I haven't found that part out. I just tried with a wireless dongle on my server to have an extra wireless connection so the stove could remain on its own ip but sadly the dongle doesn't have drivers for an ARM based Mac.

**Comment by Aohzan** [comment]
I found only two type of connection:
1. local: connect to the wifi hotspot of the stove on the same network 192.168.120.0/24
2. cloud: connect to the web service of the manufacturer, when the stove is connected to your wifi

I didn't try to connect on its IP when it is on your local network
